import type { APIGatewayProxyEventV2, APIGatewayProxyResultV2, PredictionItem } from '../types.js';
import { jsonResponse } from '../utils/response.js';
import { getPredictiveZones } from '../services/predictiveEngine.js';
import { getCachedData, setCachedData } from '../services/cache.js';
import { macroStamp } from '../services/marketData/fred.js';
import { putItem } from '../services/dynamodb.js';

/**
 * Record an actionable plan so the scheduled evaluator (EvaluateQuantRule,
 * cron(30 21 ? * MON-FRI)) can grade it and feed FACTOR_STATS/SETUP_STATS.
 *
 * Previously only screenerService persisted predictions, so plans generated by
 * opening the AI Trade Plan panel were never written down — the learning loop
 * had almost nothing to grade and every symbol stayed pinned to the "insufficient
 * evidence" prior no matter how many plans were viewed.
 *
 * The sort key is bucketed to the calendar day rather than the exact timestamp:
 * re-opening the panel for the same symbol overwrites that day's row instead of
 * appending near-identical setups, which would over-weight whichever symbols
 * happen to get viewed most in the aggregate factor stats.
 */
async function persistPrediction(symbol: string, data: any): Promise<void> {
  const plan = data?.aiThesis?.tradePlan;
  // Only actionable plans are gradeable — gradeOutcome needs entry/stop/target.
  if (!plan || !plan.bias || plan.bias === 'NO TRADE') return;
  if (typeof plan.trigger !== 'number' || typeof plan.stop !== 'number') return;

  // majorResistance is T1 for both LONG and SHORT (compositeScore.ts computes
  // rewardRisk from it either way) — grading against stretchTarget (T2) for SHORT
  // would score against a farther level than the R:R shown to the user promised.
  const target = plan.majorResistance;
  if (typeof target !== 'number') return;

  const now = new Date();
  // Recorded alongside the plan so the macro question can be revisited on live
  // outcomes. Awaited but non-fatal — macroStamp swallows its own failures.
  const macro = await macroStamp();
  const item: PredictionItem = {
    pk: `PREDICTION#${symbol}`,
    sk: `TIMESTAMP#${now.toISOString().slice(0, 10)}`,
    symbol,
    source: 'TRADE_PLAN',
    currentPrice: data.currentPrice,
    zones: data.zones,
    aiThesis: data.aiThesis,
    createdAt: now.toISOString(),
    setupType: plan.archetype,
    entry: plan.trigger,
    stop: plan.stop,
    target,
    macro,
  };
  await putItem(item);
}

export async function getPredictionZonesRoute(
  event: APIGatewayProxyEventV2,
  params: Record<string, string>,
): Promise<APIGatewayProxyResultV2> {
  const symbol = params['symbol']?.toUpperCase();
  if (!symbol) {
    return jsonResponse(400, { error: '"symbol" is required' });
  }

  const forceRefresh = event.queryStringParameters?.refresh === 'true';
  const expiry = event.queryStringParameters?.expiry;
  /**
   * Deterministic-only mode. Returns the identical payload minus the LLM
   * narration, with no AI round trip anywhere on the path, so the chart can
   * draw its zones while the narrated plan is still being built.
   *
   * Kept as a flag on this route rather than a second route because every line
   * below — the ET-day cache bucket, the error shape, the response contract —
   * applies unchanged; a parallel route would have to duplicate all of it and
   * would drift.
   */
  const fast = event.queryStringParameters?.fast === 'true';

  // One plan per symbol per trading day. These are swing/options setups held for
  // days-to-weeks off completed daily bars, so the thesis does not change within a
  // session — regenerating hourly (the previous 1h TTL) produced a plan that drifted
  // through the day off the same underlying data, and made the levels you were
  // watching move under you. Intraday setups are the screener's job.
  // Bucketing the key by ET date means the first request of each day computes and
  // every later one reuses it; ?refresh=true still forces a rebuild.
  const etDate = new Date().toLocaleDateString('en-CA', { timeZone: 'America/New_York' });
  // Separate namespace for the fast payload. Sharing one key would let a
  // narration-free result be served to callers asking for the full plan —
  // silently and indistinguishably, since the two differ only by two prose
  // fields.
  const cacheKey = `PREDICTIVE_ZONES${fast ? '_FAST' : ''}_V7#${symbol}#${etDate}${expiry ? '#' + expiry : ''}`;
  const CACHE_TTL_SECONDS = 36 * 60 * 60; // outlives the day's key so weekends reuse Friday's

  if (!forceRefresh) {
    const cached = await getCachedData<any>(cacheKey);
    if (cached) {
      return jsonResponse(200, cached);
    }
  }

  try {
    const data = await getPredictiveZones(symbol, expiry, undefined, { skipAi: fast });

    await setCachedData(cacheKey, { ...data, aiPending: fast }, CACHE_TTL_SECONDS);

    // Persist on fresh computation only (cache hits return early above), so this
    // writes at most once per hour per symbol regardless of how often the panel
    // is opened. Never fail the request over a bookkeeping write.
    //
    // NOT on the fast path: the chart fires both requests for the same symbol on
    // the same day, and the graded row must be the narrated plan the user was
    // actually shown. Writing from both would have the fast one land first and
    // the full one overwrite it — same-day sort key, so no duplicate row, but
    // the learning loop would briefly hold a plan nobody saw.
    if (!fast) {
      try {
        await persistPrediction(symbol, data);
      } catch (err) {
        console.error(`[Predictive] Failed to persist prediction for ${symbol}:`, err);
      }
    }

    return jsonResponse(200, { ...data, aiPending: fast });
  } catch (err: any) {
    console.error('Predictive Engine Error:', err);
    return jsonResponse(500, { error: err.message });
  }
}
